databases:
  - name: cuddly-eureka
    databaseName: cuddly-eureka
    user: cuddly-eureka
    plan: free

services:
  - type: web
    name: cuddly-eureka
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cuddly-eureka
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2

